/**
 * The generated-source-of-truth half of the bundle-size pipeline: turns a
 * fresh measurement (scripts/lib/bundle-measure.ts) into the exact bytes
 * that belong in every place scrollsheet's shipped size gets quoted, and
 * exposes a pure freshness check reused by three call sites so none of them
 * duplicate this logic:
 *   - scripts/check-size.ts        — fails `bun run size` (already a
 *     post-build CI step) if any target has drifted.
 *   - scripts/sync-sizes.ts        — writes the fresh numbers (default) or
 *     just reports staleness without writing (`--check`).
 *   - tests/unit/bundle-sizes.test.ts    — same gate, as part of `bun test tests/unit`.
 *
 * Two kinds of target:
 *   1. docs/src/lib/bundle-sizes.generated.ts — a real TS module the Astro
 *      site imports directly, so its numbers can't drift by construction.
 *   2. Markdown/plain-text files that can't import: README.md, llms.txt,
 *      .claude/ROADMAP.md, docs/public/llms-full.txt. These carry the
 *      number between a `<!--size:KEY.metric:decimals-->...<!--/size-->`
 *      marker pair — an HTML comment, invisible wherever the file renders
 *      as markdown, and the only part of the file this module ever rewrites.
 *      `decimals` lives in the marker itself because the same figure is
 *      quoted at different precisions in different places (README rounds to
 *      1 decimal, .claude/ROADMAP.md and the FAQ to 2, llms.txt to a bare
 *      "~N" whole number).
 */
import type { BundleSizes, SizeKey } from "./bundle-measure";

export const SIZE_ENTRY_KEYS = ["index", "drawer", "toast", "all", "auto"] as const;
export type SizeEntryKey = SizeKey;

export interface SizeEntry {
  gzipKb: number;
  brotliKb: number;
}

export type SizeReport = Record<SizeEntryKey, SizeEntry>;

// Two-decimal precision matches the finest-grained quote anywhere in the
// docs (.claude/ROADMAP.md, the FAQ) — rounding once, here, means every
// coarser rendering (1 decimal, whole-number) is a re-round of the SAME
// stored figure instead of a second independent measurement.
function toKb(bytes: number): number {
  return Math.round((bytes / 1024) * 100) / 100;
}

export function buildSizeReport(measurements: Record<SizeEntryKey, BundleSizes>): SizeReport {
  const report = {} as SizeReport;
  for (const key of SIZE_ENTRY_KEYS) {
    const sizes = measurements[key];
    if (!sizes) throw new Error(`size-report: missing measurement for ${key}`);
    report[key] = { gzipKb: toKb(sizes.gzip), brotliKb: toKb(sizes.brotli) };
  }
  return report;
}

export const GENERATED_MODULE_PATH = "docs/src/lib/bundle-sizes.generated.ts";

export const MARKED_TEXT_FILES = [
  "README.md",
  "llms.txt",
  ".claude/ROADMAP.md",
  "docs/public/llms-full.txt",
] as const;

export function generateModuleSource(report: SizeReport): string {
  const entries = SIZE_ENTRY_KEYS.map(
    (key) => `  ${key}: { gzipKb: ${report[key].gzipKb}, brotliKb: ${report[key].brotliKb} },`,
  ).join("\n");
  return `// GENERATED by \`bun run scripts/sync-sizes.ts\` — do not hand-edit.
// A freshness check (scripts/check-size.ts, tests/unit/bundle-sizes.test.ts) fails
// the build if this drifts from a fresh esbuild+gzip/brotli measurement of
// the entry. Regenerate with \`bun run scripts/sync-sizes.ts\` after any
// change that could move the bundle (src/**, tsdown.config.ts).
// Each key is an import shape, not a file: \`index\` is what
// \`import { Sheet } from 'scrollsheet'\` costs, \`drawer\` is \`{ Drawer }\`,
// \`toast\` is \`{ Toaster, toast }\` — all from the same entry.
export interface BundleSize {
  gzipKb: number;
  brotliKb: number;
}

export const BUNDLE_SIZES: Record<"index" | "drawer" | "dialog" | "toast" | "all" | "auto", BundleSize> = {
${entries}
};
`;
}

const MARKER_RE = /<!--size:(index|drawer|toast|all|auto)\.(gzip|brotli):(\d)-->[^<]*<!--\/size-->/g;

export function renderMarkedRegions(content: string, report: SizeReport): string {
  return content.replace(MARKER_RE, (_match, key: string, metric: string, decimalsStr: string) => {
    const entry = report[key as SizeEntryKey];
    const value = metric === "gzip" ? entry.gzipKb : entry.brotliKb;
    const decimals = Number(decimalsStr);
    return `<!--size:${key}.${metric}:${decimalsStr}-->${value.toFixed(decimals)}<!--/size-->`;
  });
}

const REPO_ROOT = new URL("../../", import.meta.url);

export function repoPath(relPath: string): URL {
  return new URL(relPath, REPO_ROOT);
}

async function readIfExists(url: URL): Promise<string> {
  const file = Bun.file(url);
  return (await file.exists()) ? file.text() : "";
}

export interface FreshnessTarget {
  /** Repo-relative path, for logging — one of GENERATED_MODULE_PATH or MARKED_TEXT_FILES. */
  path: string;
  current: string;
  expected: string;
}

export async function computeFreshnessTargets(report: SizeReport): Promise<FreshnessTarget[]> {
  const targets: FreshnessTarget[] = [];

  const moduleUrl = repoPath(GENERATED_MODULE_PATH);
  targets.push({
    path: GENERATED_MODULE_PATH,
    current: await readIfExists(moduleUrl),
    expected: generateModuleSource(report),
  });

  for (const relPath of MARKED_TEXT_FILES) {
    const current = await readIfExists(repoPath(relPath));
    targets.push({ path: relPath, current, expected: renderMarkedRegions(current, report) });
  }

  return targets;
}

export async function findStaleTargets(report: SizeReport): Promise<FreshnessTarget[]> {
  const targets = await computeFreshnessTargets(report);
  return targets.filter((t) => t.current !== t.expected);
}
