/**
 * core.css / sonner/toast.css (authored, commented) → *-css.generated.ts
 * (minified template strings the library injects). Checked in so src
 * consumers (playground, e2e fixtures, tsdown) all just import a plain TS
 * module; `bun run build` regenerates, and tests/unit/css-minify.test.ts fails if
 * either is stale.
 */
import { minifyCss } from "./minify-css";

interface CssTarget {
  srcUrls: URL[];
  outUrl: URL;
  exportName: string;
  srcBasename: string;
  /** Extra import lines the generated module needs (e.g. spring interpolation). */
  header?: string;
}

const TARGETS: CssTarget[] = [
  {
    // core.css + widgets.css concatenate into one CORE_CSS string — the
    // split exists only for the 1500-line src file cap.
    srcUrls: [
      new URL("../packages/scrollsheet/src/internal/core.css", import.meta.url),
      new URL("../packages/scrollsheet/src/internal/widgets.css", import.meta.url),
    ],
    outUrl: new URL("../packages/scrollsheet/src/internal/core-css.generated.ts", import.meta.url),
    exportName: "CORE_CSS",
    srcBasename: "core.css + widgets.css",
    header: 'import { SHEET_SPRING } from "../motion/spring";\n\n',
  },
  {
    srcUrls: [new URL("../packages/scrollsheet/src/toast/toast.css", import.meta.url)],
    outUrl: new URL("../packages/scrollsheet/src/toast/toast-css.generated.ts", import.meta.url),
    exportName: "TOAST_CSS",
    srcBasename: "toast.css",
  },
];

for (const target of TARGETS) {
  const parts = await Promise.all(target.srcUrls.map((u) => Bun.file(u).text()));
  const css = parts.join("\n");
  const min = minifyCss(css);
  const out = `// Generated by scripts/gen-css.ts — do not edit. Authored CSS: ./${target.srcBasename}
${target.header ?? ""}export const ${target.exportName} = \`${min}\`;
`;
  await Bun.write(target.outUrl, out);
  console.log(`${target.outUrl.pathname.split("/").pop()} written (${min.length} chars)`);
}
