// GENERATED by `bun run scripts/sync-sizes.ts` — do not hand-edit.
// A freshness check (scripts/check-size.ts, tests/unit/bundle-sizes.test.ts) fails
// the build if this drifts from a fresh esbuild+gzip/brotli measurement of
// the entry. Regenerate with `bun run scripts/sync-sizes.ts` after any
// change that could move the bundle (src/**, tsdown.config.ts).
// Each key is an import shape, not a file: `index` is what
// `import { Sheet } from 'scrollsheet'` costs, `drawer` is `{ Drawer }`,
// `toast` is `{ Toaster, toast }` — all from the same entry.
export interface BundleSize {
  gzipKb: number;
  brotliKb: number;
}

export const BUNDLE_SIZES: Record<"index" | "drawer" | "dialog" | "toast" | "all" | "auto", BundleSize> = {
  index: { gzipKb: 18.02, brotliKb: 15.98 },
  drawer: { gzipKb: 18.8, brotliKb: 16.7 },
  dialog: { gzipKb: 17.55, brotliKb: 15.61 },
  toast: { gzipKb: 6.59, brotliKb: 5.95 },
  all: { gzipKb: 24.43, brotliKb: 21.64 },
  auto: { gzipKb: 22.29, brotliKb: 19.46 },
};
