// GENERATED by `bun run scripts/sync-sizes.ts` — do not hand-edit.
// A freshness check (scripts/check-size.ts, tests/unit/bundle-sizes.test.ts) fails
// the build if this drifts from a fresh esbuild+gzip/brotli measurement of
// the entry. Regenerate with `bun run scripts/sync-sizes.ts` after any
// change that could move the bundle (src/**, tsdown.config.ts).
// Each key is an import shape, not a file: `index` is what
// `import { Sheet } from 'scrollsheet'` costs, `drawer` is `{ Drawer }`,
// `toast` is `{ Toaster, toast }` — all from the same entry.
export interface BundleSize {
  gzipKb: number;
  brotliKb: number;
}

export const BUNDLE_SIZES: Record<"index" | "drawer" | "toast" | "all" | "auto", BundleSize> = {
  index: { gzipKb: 18.6, brotliKb: 16.52 },
  drawer: { gzipKb: 19.8, brotliKb: 17.5 },
  toast: { gzipKb: 6.79, brotliKb: 6.11 },
  all: { gzipKb: 25.57, brotliKb: 22.58 },
  auto: { gzipKb: 22.59, brotliKb: 19.78 },
};
